name: 'Frontend Continuous Integration'
on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: run lint
        run: npx eslint --fix .

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code 
        uses: actions/checkout@v3
      - name: Setup NodeJS 
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: test
        run: npm run test

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: starter/frontend
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: ${{github.workspace}}/starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: build run
        run: npm run test


 